# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the i2c algorithms
#

obj-$(CPTCFG_I2C_ALGOBIT)	+= i2c-algo-bit.o
obj-$(CPTCFG_I2C_ALGOPCF)	+= i2c-algo-pcf.o
obj-$(CPTCFG_I2C_ALGOPCA)	+= i2c-algo-pca.o

ccflags-$(CPTCFG_I2C_DEBUG_ALGO) := -DDEBUG
